spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_example
    username: springuser
    password: ThePassword
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

logging: 
  pattern:
    console: "%d{dd-MM-yy HH:mm:ss.SSS} %-5level %logger : %msg%n"    
  level:
    org.springframework: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: trace
